FROM ubuntu:18.04

RUN apt-get update -y  && apt-get install -y python3-pip python3-dev

CMD [ "ufw allow 5000" ]

COPY ./reqs.txt /app/reqs.txt

WORKDIR /app

RUN pip3 install -r reqs.txt

COPY ./myAPI.py /app

ENTRYPOINT ["python3"]

CMD [ "myAPI.py" ]